name: base
channels:
  - defaults
dependencies:
  - anaconda-anon-usage=0.4.4
  - archspec=0.2.3
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - conda=24.7.1
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=24.7.0
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - console_shortcut_miniconda=0.1.1
  - cryptography=42.0.5
  - distro=1.9.0
  - expat=2.6.2
  - fmt=9.1.0
  - frozendict=2.4.2
  - idna=3.7
  - jsonpatch=1.33
  - jsonpointer=2.1
  - libarchive=3.6.2
  - libcurl=8.7.1
  - libffi=3.4.4
  - libiconv=1.16
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libsolv=0.7.24
  - libssh2=1.11.0
  - libxml2=2.13.1
  - lz4-c=1.9.4
  - menuinst=2.1.2
  - openssl=3.0.14
  - packaging=24.1
  - pcre2=10.42
  - pip=24.2
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - powershell_shortcut_miniconda=0.0.1
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.12.4
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.3
  - ruamel.yaml=0.17.21
  - setuptools=72.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tqdm=4.66.4
  - truststore=0.8.0
  - tzdata=2024a
  - urllib3=2.2.2
  - vc=14.40
  - vs2015_runtime=14.40.33807
  - wheel=0.43.0
  - win_inet_pton=1.1.0
  - xz=5.4.6
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
